### ISSUE TITLE
For forecasting tasks in this repository, eval_forecasting() has bugs can lead to unacceptable better forecasting results

### ISSUE THREAD

**Issue by wiwi** [xingyu617/SimTS_Representation_Learning#5] opened 2023-05-16 05:05 UTC
In the eval_forecasting() function, the authors split the training, validation, and test sets after encoding all data as representation. Considering that the convolutional network is used to construct the encoder, the part information of test data will inevitably leak into the training set and validation set. Authors' code can get an additional 10-12% MSE boost on Electricity datasets, which is clearly unacceptable. Therefore, the results in the author's paper are also untrustworthy.

**Comment by xcvil** [comment] 2023-05-16 10:03
Hi,

Thank you for your interest!

We are sorry that we did not get what you mean. Could you please provide specific codes which cause your puzzle?

BTW, the training part in eval_forecasting() is for regressor instead of encoder.

**Comment by wiwi** [comment] 2023-05-20 02:25
def eval_forecasting(model, data, train_slice, valid_slice, test_slice, scaler, pred_lens, n_covariate_cols):
    padding = 200
    print("test data:",data.shape)
    t = time.time()
    all_repr = model.encode(
        data,
        casual=True,
        sliding_length=1,
        sliding_padding=padding,
        batch_size=128
    )
    
    ts2vec_infer_time = time.time() - t
    print("all_repr",data.shape,all_repr.shape)
    train_repr = all_repr[:, train_slice]
    valid_repr = all_repr[:, valid_slice]
    test_repr = all_repr[:, test_slice]
    ... ...


Generally, when we evaluate the model, we split the dataset first and make sure there are no sharing data within these 3 sets. However, your code inputs the whole series and encode them. And then, split them into training, validation and testing sets. Now, testing set shares some information with others according to the conv kenerl of your model is so large. 
You can try another method, split the dataset first and encode them one by one, and then perform the task. I think you will find the question I mentioned above.

**Comment by wiwi** [comment] 2023-05-20 03:02
Additional, according to your splitting method, validation and testing will share some data directly. Is it right? I think you find your big bug. You should redo all experiment after fix it and revise your paper even if not publish yet.

**Comment by xcvil** [comment] 2023-05-20 08:30
> def eval_forecasting(model, data, train_slice, valid_slice, test_slice, scaler, pred_lens, n_covariate_cols): padding = 200 print("test data:",data.shape) t = time.time() all_repr = model.encode( data, casual=True, sliding_length=1, sliding_padding=padding, batch_size=128 )
> 
> ```
> ts2vec_infer_time = time.time() - t
> print("all_repr",data.shape,all_repr.shape)
> train_repr = all_repr[:, train_slice]
> valid_repr = all_repr[:, valid_slice]
> test_repr = all_repr[:, test_slice]
> ... ...
> ```
> 
> Generally, when we evaluate the model, we split the dataset first and make sure there are no sharing data within these 3 sets. However, your code inputs the whole series and encode them. And then, split them into training, validation and testing sets. Now, testing set shares some information with others according to the conv kenerl of your model is so large. You can try another method, split the dataset first and encode them one by one, and then perform the task. I think you will find the question I mentioned above.

We follow the same evaluation method published in TS2Vec (AAAI) and CoST (ICLR) for fair comparison. I guess you did not fully understand the function ```model.encode()```, which ensures that there is no information leakage during the evaluation stage. In short, the inference would be ```pad->encode->cut```. Please take a look at [this issue](https://github.com/yuezhihan/ts2vec/issues/7) for a better understanding.

**Comment by xcvil** [comment] 2023-05-20 08:57
> Additional, according to your splitting method, validation and testing will share some data directly. Is it right? I think you find your big bug. You should redo all experiment after fix it and revise your paper even if not publish yet.

The validation and test will **not** share data directly. Please take a look at [codes](https://github.com/xingyu617/SimTS_Representation_Learning/blob/2ab5572830539b54f29de5486706382d40b2e1db/simts.py#L304-L405). I believe after checking the codes and issue mentioned above, you will have a better understanding of the inference.

P.S., I understand the splitting method is not as direct and intuitive as CV and NLP data. Since the [ETT dataset](https://github.com/zhouhaoyi/ETDataset) only has data from one machine (one sequence).

**Comment by xcvil** [comment] 2023-05-20 09:01
> In the eval_forecasting() function, the authors split the training, validation, and test sets after encoding all data as representation. Considering that the convolutional network is used to construct the encoder, the part information of test data will inevitably leak into the training set and validation set. Authors' code can get an additional 10-12% MSE boost on Electricity datasets, which is clearly unacceptable. Therefore, the results in the author's paper are also untrustworthy.

Could you please show us how did you get the value of 10-12%? If you re-implement the evaluation/inference, could you also test it in [TS2Vec](https://github.com/yuezhihan/ts2vec) and [CoST](https://github.com/salesforce/CoST/tree/main) in order to make sure your codes have no big bugs?

**Comment by wiwi** [comment] 2023-05-21 03:46
For Multivariate Froecasting tasks, we agree with you. We also think the evaluate protocol is moderate. But, if we transfer to  Univariate Forecasting, that is Table 2 in your paper, the bug we mentioned would exist. 
Addition, if we use ETTxx datasets to do it, in fact, we also cannot find the bug(Here, we donot want to discuss others' code any more.). Because, according to the set of the experiments of Univariate Forecasting about  ETTxx datasets in your code, the pretrain data is same as the training set of forecasting task. So, we change the data set to Electricity which applied by a lot of paper to study forecasting algorithm.  We use column-0 as pretrain set, and column-319 as training/validation/testing sets of forecasting task. 

According to your set, we can get the results as follows:
Dataset: electricity
Arguments: Namespace(dataset='electricity', kernels=[1, 2, 4, 8, 16, 32, 64, 128, 256], mask_dir=None, dir='./checkpoint', loader='forecast_csv_univar', gpu=0, batch_size=32, lr=0.001, repr_dims=128, max_train_length=500, K=250, iters=None, epochs=50, save_every=None, seed=1337, max_threads=None, pretrain=0, eval=True, irregular=0, experiment='base', area=None, mix=False)
Loading data... 
load_forecast_csv() (26304, 1)
done
 (1, 15782, 1)
train_data size: (1, 15782, 1)
\Loading time: 0:00:02.467408

load_forecast_csv() (26304, 1)
test data: (1, 26304, 1)
all_repr (1, 26304, 1) (1, 26304, 128)
data shape: (1, 15782, 1) (1, 5261, 1) (1, 5261, 1)
repr shape: (1, 15782, 128) (1, 5261, 128) (1, 5261, 128)
in forecasting: (5237, 128) (1, 5261, 1) (5237, 24)
test: (125688, 1) (125688, 1)
in forecasting: (5213, 128) (1, 5261, 1) (5213, 48)
test: (250224, 1) (250224, 1)
in forecasting: (5165, 128) (1, 5261, 1) (5165, 96)
test: (495840, 1) (495840, 1)
in forecasting: (5093, 128) (1, 5261, 1) (5093, 168)
test: (855624, 1) (855624, 1)
in forecasting: (4925, 128) (1, 5261, 1) (4925, 336)
test: (1654800, 1) (1654800, 1)
in forecasting: (4541, 128) (1, 5261, 1) (4541, 720)
test: (3269520, 1) (3269520, 1)
Evaluation result: {'ours': {24: {'norm': {'MSE': 0.129, 'MAE': 0.265}, 'raw': {'MSE': 8694.123, 'MAE': 68.919}}, 48: {'norm': {'MSE': 0.137, 'MAE': 0.271}, 'raw': {'MSE': 9248.758, 'MAE': 70.48}}, 96: {'norm': {'MSE': 0.135, 'MAE': 0.266}, 'raw': {'MSE': 9163.917, 'MAE': 69.294}}, 168: {'norm': {'MSE': 0.13, 'MAE': 0.256}, 'raw': {'MSE': 8770.721, 'MAE': 66.642}}, 336: {'norm': {'MSE': 0.13, 'MAE': 0.259}, 'raw': {'MSE': 8791.385, 'MAE': 67.368}}, 720: {'norm': {'MSE': 0.131, 'MAE': 0.264}, 'raw': {'MSE': 8851.491, 'MAE': 68.549}}}, 'ts2vec_infer_time': 160.2075457572937, 'lr_train_time': {24: 0.14372467994689941, 48: 0.14172697067260742, 96: 0.18780159950256348, 168: 0.2526895999908447, 336: 0.4269723892211914, 720: 0.829796552658081}, 'lr_infer_time': {24: 0.0007069110870361328, 48: 0.0008549690246582031, 96: 0.001127004623413086, 168: 0.0014667510986328125, 336: 0.0025086402893066406, 720: 0.005845308303833008}}
Finished.

==============================================================================
We adjust the code of eval_forecasting() as following:
def eval_forecasting(model, data, train_slice, valid_slice, test_slice, scaler, pred_lens, n_covariate_cols):
    padding = 200
    print("test data:",data.shape)
    t = time.time()

    # all_repr = model.encode(
    #     data[:, :, n_covariate_cols:],
    #     casual=True,
    #     sliding_length=1,
    #     sliding_padding=padding,
    #     batch_size=128
    # )
    # print("all_repr",data.shape, all_repr.shape)
    # train_repr = all_repr[:, train_slice]
    # valid_repr = all_repr[:, valid_slice]
    # test_repr = all_repr[:, test_slice]
    


    train_data = data[:, train_slice, n_covariate_cols:]
    valid_data = data[:, valid_slice, n_covariate_cols:]
    test_data = data[:, test_slice, n_covariate_cols:]
    print("data shape:", train_data.shape, valid_data.shape, test_data.shape)

    train_repr = model.encode(
        train_data,
        casual=True,
        sliding_length=1,
        sliding_padding=padding,
        batch_size=128
    )
    valid_repr = model.encode(
        valid_data,
        casual=True,
        sliding_length=1,
        sliding_padding=padding,
        batch_size=128
    )
    test_repr = model.encode(
        test_data,
        casual=True,
        sliding_length=1,
        sliding_padding=padding,
        batch_size=128
    )
    ... ...

And then, we perform the same experiment and get the following results:
Dataset: electricity
Arguments: Namespace(dataset='electricity', kernels=[1, 2, 4, 8, 16, 32, 64, 128, 256], mask_dir=None, dir='./checkpoint', loader='forecast_csv_univar', gpu=0, batch_size=32, lr=0.001, repr_dims=128, max_train_length=500, K=250, iters=None, epochs=50, save_every=None, seed=1337, max_threads=None, pretrain=0, eval=True, irregular=0, experiment='base', area=None, mix=False)
Loading data... 
load_forecast_csv() (26304, 1)
done
 (1, 15782, 1)
train_data size: (1, 15782, 1)
\Loading time: 0:00:02.495299

load_forecast_csv() (26304, 1)
test data: (1, 26304, 1)
data shape: (1, 15782, 1) (1, 5261, 1) (1, 5261, 1)
repr shape: (1, 15782, 128) (1, 5261, 128) (1, 5261, 128)
in forecasting: (5237, 128) (1, 5261, 1) (5237, 24)
test: (125688, 1) (125688, 1)
in forecasting: (5213, 128) (1, 5261, 1) (5213, 48)
test: (250224, 1) (250224, 1)
in forecasting: (5165, 128) (1, 5261, 1) (5165, 96)
test: (495840, 1) (495840, 1)
in forecasting: (5093, 128) (1, 5261, 1) (5093, 168)
test: (855624, 1) (855624, 1)
in forecasting: (4925, 128) (1, 5261, 1) (4925, 336)
test: (1654800, 1) (1654800, 1)
in forecasting: (4541, 128) (1, 5261, 1) (4541, 720)
test: (3269520, 1) (3269520, 1)
Evaluation result: {'ours': {24: {'norm': {'MSE': 0.145, 'MAE': 0.279}, 'raw': {'MSE': 9837.796, 'MAE': 72.452}}, 48: {'norm': {'MSE': 0.156, 'MAE': 0.286}, 'raw': {'MSE': 10586.859, 'MAE': 74.37}}, 96: {'norm': {'MSE': 0.154, 'MAE': 0.281}, 'raw': {'MSE': 10446.896, 'MAE': 73.034}}, 168: {'norm': {'MSE': 0.145, 'MAE': 0.268}, 'raw': {'MSE': 9781.048, 'MAE': 69.8}}, 336: {'norm': {'MSE': 0.145, 'MAE': 0.271}, 'raw': {'MSE': 9779.736, 'MAE': 70.418}}, 720: {'norm': {'MSE': 0.147, 'MAE': 0.277}, 'raw': {'MSE': 9964.939, 'MAE': 72.028}}}, 'ts2vec_infer_time': 157.5175256729126, 'lr_train_time': {24: 0.14461994171142578, 48: 0.1420578956604004, 96: 0.18578219413757324, 168: 0.251509428024292, 336: 0.4230043888092041, 720: 0.8310141563415527}, 'lr_infer_time': {24: 0.0007212162017822266, 48: 0.0008454322814941406, 96: 0.0011141300201416016, 168: 0.0014810562133789062, 336: 0.002485036849975586, 720: 0.0044040679931640625}}
Finished.

============================================================================
your code:    avg mse=0.132
after adjust:  avg mse=0.149


============================================================================
Conclusion:
We think you make a mistake when you collect results of Univariate Forecasting because you followed the code of Multivariate Froecasting. For Multivariate Froecasting, the evaluate code is right. However, for Univariate Forecasting, such code is wrong.

**Comment by wiwi** [comment] 2023-05-21 03:48
> 

Just because you follow the method of TS2VEC and CoST to perform Univariate Forecasting.

**Comment by wiwi** [comment] 2023-05-21 03:53
![image](https://github.com/xingyu617/SimTS_Representation_Learning/assets/108532/45ce92b0-fe73-43da-a8ce-e820bcc236c9)

Just because you followed the method of TS2VEC to perform Univariate Forecasting. And, the published papers not means all of their content or code are absolute right!

**Comment by wiwi** [comment] 2023-05-21 03:55
![image](https://github.com/xingyu617/SimTS_Representation_Learning/assets/108532/8b6d5391-5cb1-4da3-85c9-b1d141cde9e1)


Just because you followed the method of TS2VEC about Multivariate Froecasting to perform Univariate Forecasting.  Univariate Forecasting and Multivariate Froecasting are different.

**Comment by xcvil** [comment] 2023-05-22 14:38
> We use column-0 as pretrain set, and column-319 as training/validation/testing sets of forecasting task.

Could I ask how did you preprocess the electricity dataset? We would like to reproduce your results to see where is the bug you mentioned.

**Comment by xcvil** [comment] 2023-05-22 14:46
> For Multivariate Froecasting tasks, we agree with you. We also think the evaluate protocol is moderate. But, if we transfer to Univariate Forecasting, that is Table 2 in your paper, the bug we mentioned would exist.
Addition, if we use ETTxx datasets to do it, in fact, we also cannot find the bug(Here, we donot want to discuss others' code any more.). 

Did you mean that the "bug" explicitly exists in the evaluation protocol for the electricity dataset?

**Comment by wiwi** [comment] 2023-05-24 05:06
> > We use column-0 as pretrain set, and column-319 as training/validation/testing sets of forecasting task.
> 
> Could I ask how did you preprocess the electricity dataset? We would like to reproduce your results to see where is the bug you mentioned.

We followed your code and added a few rows in load_forecast_csv():

```
def load_forecast_csv(name, univar=False, train=True):
    data = pd.read_csv(f“../datasets/electricity/{name}.csv”, index_col='date', parse_dates=True)
    # data = pd.read_csv(f”../datasets/ETT-small/{name}.csv“, index_col='date', parse_dates=True)
    dt_embed = _get_time_features(data.index)
    n_covariate_cols = 0#dt_embed.shape[-1]
    
    if univar:
        n_covariate_cols = 0#dt_embed.shape[-1]
        if name in ('ETTh1', 'ETTh2', 'ETTm1', 'ETTm2'):
            data = data[['OT']]
        elif name == 'electricity':
            if train:  # for pretrain
                data = data[['0']]
            else:
                data = data[['319']]
        else:
            data = data.iloc[:, -1:]
```

**Comment by wiwi** [comment] 2023-05-24 05:17
> > For Multivariate Froecasting tasks, we agree with you. We also think the evaluate protocol is moderate. But, if we transfer to Univariate Forecasting, that is Table 2 in your paper, the bug we mentioned would exist.
> > Addition, if we use ETTxx datasets to do it, in fact, we also cannot find the bug(Here, we donot want to discuss others' code any more.).
> 
> Did you mean that the "bug" explicitly exists in the evaluation protocol for the electricity dataset?

In fact, I check the code of TS2VEC, and find this repository follows the evaluation protocol and some code. As you said, if this repository with a bug then the TS2VEC meets the same bug too. That's right, TS2VEC also meets this bug when evaluate univariate forecasting. So, I guess they inherit the evaluation code from multivariate forecasting. Because multivariate forecasting will not input target series into the model, so there is no information leaking. However, for univariate forecasting, the look back series is posed as input X, so the evaluation code of multivariate forecasting will lead to information leaking. I hope you can understand my words.

**Comment by xcvil** [comment] 2023-05-24 08:35
> > > We use column-0 as pretrain set, and column-319 as training/validation/testing sets of forecasting task.
> 
> > 
> 
> > Could I ask how did you preprocess the electricity dataset? We would like to reproduce your results to see where is the bug you mentioned.
> 
> 
> 
> We followed your code and added a few rows in load_forecast_csv():
> 
> 
> 
> ```
> 
> def load_forecast_csv(name, univar=False, train=True):
> 
>     data = pd.read_csv(f“../datasets/electricity/{name}.csv”, index_col='date', parse_dates=True)
> 
>     # data = pd.read_csv(f”../datasets/ETT-small/{name}.csv“, index_col='date', parse_dates=True)
> 
>     dt_embed = _get_time_features(data.index)
> 
>     n_covariate_cols = 0#dt_embed.shape[-1]
> 
>     
> 
>     if univar:
> 
>         n_covariate_cols = 0#dt_embed.shape[-1]
> 
>         if name in ('ETTh1', 'ETTh2', 'ETTm1', 'ETTm2'):
> 
>             data = data[['OT']]
> 
>         elif name == 'electricity':
> 
>             if train:  # for pretrain
> 
>                 data = data[['0']]
> 
>             else:
> 
>                 data = data[['319']]
> 
>         else:
> 
>             data = data.iloc[:, -1:]
> 
> ```
> 
> 


Is this your ``` load_forecast_csv() ``` function? Did you keep the rest of the original codes?

**Comment by xcvil** [comment] 2023-05-24 14:45
> > > For Multivariate Froecasting tasks, we agree with you. We also think the evaluate protocol is moderate. But, if we transfer to Univariate Forecasting, that is Table 2 in your paper, the bug we mentioned would exist.
> > > Addition, if we use ETTxx datasets to do it, in fact, we also cannot find the bug(Here, we donot want to discuss others' code any more.).
> > 
> > 
> > Did you mean that the "bug" explicitly exists in the evaluation protocol for the electricity dataset?
> 
> In fact, I check the code of TS2VEC, and find this repository follows the evaluation protocol and some code. As you said, if this repository with a bug then the TS2VEC meets the same bug too. That's right, TS2VEC also meets this bug when evaluate univariate forecasting. So, I guess they inherit the evaluation code from multivariate forecasting. Because multivariate forecasting will not input target series into the model, so there is no information leaking. However, for univariate forecasting, the look back series is posed as input X, so the evaluation code of multivariate forecasting will lead to information leaking. I hope you can understand my words.

Yes... I got your point. You were saying that the evaluation protocol for multivariate is rigorous, and thus the results for multivariate are correct. But there are bugs with univariate time series (which we are trying to understand and reproduce your results).

**Comment by xcvil** [comment] 2023-05-25 09:12
> Because multivariate forecasting will not input target series into the model, so there is no information leaking. 

Could I ask what you mean by this? From my point of view, if multivariate forecasting does not input the target, so does univariate.

**Comment by wiwi** [comment] 2023-05-25 23:35
> > > > We use column-0 as pretrain set, and column-319 as training/validation/testing sets of forecasting task.
> > 
> > 
> > > 
> > 
> > 
> > > Could I ask how did you preprocess the electricity dataset? We would like to reproduce your results to see where is the bug you mentioned.
> > 
> > 
> > We followed your code and added a few rows in load_forecast_csv():
> > ```
> > 
> > def load_forecast_csv(name, univar=False, train=True):
> > 
> >     data = pd.read_csv(f“../datasets/electricity/{name}.csv”, index_col='date', parse_dates=True)
> > 
> >     # data = pd.read_csv(f”../datasets/ETT-small/{name}.csv“, index_col='date', parse_dates=True)
> > 
> >     dt_embed = _get_time_features(data.index)
> > 
> >     n_covariate_cols = 0#dt_embed.shape[-1]
> > 
> >     
> > 
> >     if univar:
> > 
> >         n_covariate_cols = 0#dt_embed.shape[-1]
> > 
> >         if name in ('ETTh1', 'ETTh2', 'ETTm1', 'ETTm2'):
> > 
> >             data = data[['OT']]
> > 
> >         elif name == 'electricity':
> > 
> >             if train:  # for pretrain
> > 
> >                 data = data[['0']]
> > 
> >             else:
> > 
> >                 data = data[['319']]
> > 
> >         else:
> > 
> >             data = data.iloc[:, -1:]
> > ```
> 
> Is this your `load_forecast_csv()` function? Did you keep the rest of the original codes?

Yes

**Comment by wiwi** [comment] 2023-05-25 23:39
> > Because multivariate forecasting will not input target series into the model, so there is no information leaking.
> 
> Could I ask what you mean by this? From my point of view, if multivariate forecasting does not input the target, so does univariate.

The univariable is using the historical sequence to predict the future sequence, but if you follow this code, the test sequence leaks into the training or validation sequence.

**Comment by xcvil** [comment] 2023-05-26 13:21
Dear wiwi,

Besides, regarding your evaluation protocol, there might be information leakage between column-0 and column-319.

I guess your problem was well addressed with https://github.com/yuezhihan/ts2vec/issues/35. So, I will close this issue as solved. Please follow the original codes for evaluation strictly and modify the codes thoughtfully. If you still have problems, please reopen this issue.

Cheers,
SimTS authors

**Closed as completed by xcvil** 2023-05-26 13:21 UTC

**Comment by xcvil** [comment] 2023-05-26 13:28
Please note that after careful argument and justification, we guarantee our final results are accurate and precise. We will release more evaluation results upon acceptance.
